import assert from 'node:assert/strict';
import {documents,chunks,applicable,appliesTo,medium,status,validDate,retrieve,clarify,lookupVersion} from '../lib/knowledge';
const doc=(id:string)=>documents.find(x=>x.id===id)!;
assert.equal(applicable(doc('gb-urban'),'2026-02-28'),false);
assert.equal(applicable(doc('gb-urban'),'2026-03-01'),true);
assert.equal(status(doc('zj-rural-old'),'2026-09-17'),'已替代');
assert.equal(status(doc('hj-soil-old'),'2026-09-19'),'已替代');
assert.equal(applicable(doc('hj-soil'),'2026-05-31'),false);
assert.equal(applicable(doc('hj-soil'),'2026-06-01'),true);
assert.equal(validDate('2026-02-30'),false);
assert.equal(validDate('2026-13-01'),false);
assert.equal(validDate('2026-09-17'),true);
assert.equal(applicable(doc('zj-rural'),'2026-09-17'),false,'Unavailable full text must not enter retrieval');
const evidence=retrieve('浙江城镇污水处理厂适用范围和主要污染物执行依据是什么？','2026-09-17','城镇污水');
assert.ok(evidence.some(x=>x.docId==='zj-urban'));
assert.ok(evidence.every(x=>applicable(x.document,'2026-09-17')));
assert.ok(!retrieve('GB 18918 瞬时值日均值','2026-02-01','城镇污水').some(x=>x.docId==='gb-urban'));
assert.ok(clarify('农村污水排放限值','农村污水'));
assert.ok(clarify('企业废水纳管要求','城镇污水'));
assert.ok(clarify('COD多少才达标？','城镇污水'));
assert.equal(clarify('污水监测采样要求是什么？','监测管理'),null);
assert.ok(chunks.every(x=>documents.some(d=>d.id===x.docId)));
assert.ok(chunks.filter(x=>x.page!==null).every(x=>x.page!>0));
assert.ok(chunks.every(x=>!x.text.includes('\uFFFD')),'Document extraction must preserve Unicode');
assert.ok(evidence[0].docId==='zj-urban');
assert.ok(lookupVersion('DB33/973-2015 现在还能用吗？','2026-09-17')?.answer.includes('已替代'));
assert.ok(lookupVersion('2025年修改单什么时候实施？','2026-02-01')?.answer.includes('尚未实施'));
assert.equal(lookupVersion('污水采样要求','2026-09-17'),null);
assert.ok(retrieve('HJ 166-2026 对土壤样品采集和保存有哪些要求？','2026-09-19','土壤采样').some(x=>x.docId==='hj-soil'));
assert.ok(retrieve('HJ 493-2009 对水样容器和保护剂有哪些要求？','2026-09-19','水样采集').some(x=>x.docId==='hj-water-preserve'));
assert.ok(retrieve('地表水采样记录包括什么？','2026-09-19','水样采集').every(x=>x.document.topic==='水样采集'));
const jiangsu=retrieve('江苏城镇污水处理厂适用范围和排放限值','2026-09-19','城镇污水','江苏省');
assert.ok(jiangsu.some(x=>x.docId==='js-urban'));
assert.ok(jiangsu.every(x=>x.document.region==='江苏省'||x.document.region==='全国'));
assert.ok(retrieve('北京农村生活污水处理设施适用范围','2026-09-19','农村污水','北京市').some(x=>x.docId==='bj-rural'));
assert.ok(retrieve('上海企业污水间接排放适用什么标准','2026-09-19','企业纳管','上海市').some(x=>x.docId==='sh-comprehensive'));
assert.equal(applicable(doc('sh-rural-old'),'2026-09-19'),false);
assert.ok(clarify('上海农村污水排放限值','农村污水','上海市')?.includes('废止'));
assert.equal(applicable(doc('hj-stack-voc'),'2026-03-31'),false);
assert.equal(applicable(doc('hj-stack-voc'),'2026-04-01'),true);
assert.equal(applicable(doc('hj-stack-voc-old'),'2026-09-20'),false);
assert.equal(applicable(doc('hj-outlet-site'),'2026-09-20'),false);
assert.equal(applicable(doc('hj-outlet-site'),'2027-01-01'),true);
const gas=retrieve('HJ 732-2025 固定污染源废气 VOC 气袋采样要求','2026-09-20','气体采样');
assert.ok(gas.some(x=>x.docId==='hj-stack-voc'));
assert.ok(gas.every(x=>x.document.topic==='气体采样'));
assert.ok(retrieve('GB/T 16157 气态污染物采样位置和采样系统','2026-09-20','气体采样').some(x=>x.docId==='gb-stack-sampling'));
assert.ok(retrieve('HJ 194-2017 环境空气吸收管采样流量校准','2026-09-20','气体采样').some(x=>x.docId==='hj-air-manual'));
assert.ok(clarify('废气排放限值是多少','气体采样')?.includes('尚未覆盖'));
assert.ok(lookupVersion('HJ 732-2014 现在还能用吗？','2026-09-20')?.answer.includes('已替代'));
assert.equal(medium(doc('hj-water-preserve')),'水');
assert.equal(medium(doc('hj-soil-voc')),'土壤');
assert.equal(medium(doc('bj-stack-voc')),'气体');
assert.equal(appliesTo(doc('hj-soil-voc'),'上海市'),true);
assert.equal(appliesTo(doc('bj-stack-voc'),'上海市'),false);
assert.equal(appliesTo(doc('yrd-stack-monitor'),'江苏省'),true);
assert.equal(appliesTo(doc('yrd-stack-monitor'),'北京市'),false);
assert.ok(retrieve('DB11/T 1484-2017 固定污染源废气 VOC 如何采样？','2026-09-20','气体采样','北京市').some(x=>x.docId==='bj-stack-voc'));
const joint=retrieve('DB32/T 310003-2021 固定污染源废气现场监测要求','2026-09-20','气体采样','江苏省');
assert.ok(joint.some(x=>x.docId==='yrd-stack-monitor'));
assert.ok(joint.every(x=>appliesTo(x.document,'江苏省')));
assert.ok(retrieve('HJ 1019-2019 土壤挥发性有机物怎样采样？','2026-09-20','土壤采样','上海市').some(x=>x.docId==='hj-soil-voc'));
console.log('Knowledge checks passed: dates, versions, region inheritance, media categories, retrieval and source integrity.');
